/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author user
 */
public class menu extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mksr = new javax.swing.JMenu();
        mkasir = new javax.swing.JMenuItem();
        mbrg = new javax.swing.JMenuItem();
        mplg = new javax.swing.JMenuItem();
        mnota = new javax.swing.JMenu();
        nota = new javax.swing.JMenuItem();
        lapPel = new javax.swing.JMenu();
        laporan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SISTEM APLIKASI PENJUALAN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Pemrograman Visual");

        mksr.setText("Master");
        mksr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mksrActionPerformed(evt);
            }
        });

        mkasir.setText("Kasir");
        mkasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mkasirActionPerformed(evt);
            }
        });
        mksr.add(mkasir);

        mbrg.setText("Barang");
        mbrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbrgActionPerformed(evt);
            }
        });
        mksr.add(mbrg);

        mplg.setText("Pelanggan");
        mplg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mplgActionPerformed(evt);
            }
        });
        mksr.add(mplg);

        jMenuBar1.add(mksr);

        mnota.setText("Transaksi");
        mnota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnotaActionPerformed(evt);
            }
        });

        nota.setText("Nota");
        nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaActionPerformed(evt);
            }
        });
        mnota.add(nota);

        jMenuBar1.add(mnota);

        lapPel.setText("Laporan");

        laporan.setText("Laporan Data Pelanggan");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        lapPel.add(laporan);

        jMenuBar1.add(lapPel);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnotaActionPerformed
       new nota().setVisible(true);
    }//GEN-LAST:event_mnotaActionPerformed

    private void notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaActionPerformed
       new nota().setVisible(true);
    }//GEN-LAST:event_notaActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        try{
            String path = "./src/report/reportPel.jasper";
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada" + ex);
        }
    }//GEN-LAST:event_laporanActionPerformed

    private void mksrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mksrActionPerformed

    }//GEN-LAST:event_mksrActionPerformed

    private void mbrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbrgActionPerformed
        new barang().setVisible(true);
    }//GEN-LAST:event_mbrgActionPerformed

    private void mplgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mplgActionPerformed
        new tampilan().setVisible(true);
    }//GEN-LAST:event_mplgActionPerformed

    private void mkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mkasirActionPerformed
        new kassir().setVisible(true);
    }//GEN-LAST:event_mkasirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu lapPel;
    private javax.swing.JMenuItem laporan;
    private javax.swing.JMenuItem mbrg;
    private javax.swing.JMenuItem mkasir;
    private javax.swing.JMenu mksr;
    private javax.swing.JMenu mnota;
    private javax.swing.JMenuItem mplg;
    private javax.swing.JMenuItem nota;
    // End of variables declaration//GEN-END:variables
}
